var tableData = [
{id:11, number:11, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Silk Tablecloth", productcoinname:"", productquality:107.1, productremaining:1},
{id:13, number:13, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:20, productname:"Linen Shirt", productcoinname:"", productquality:98.3, productremaining:3},
{id:13, number:13, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:20, productname:"Linen Pants", productcoinname:"", productquality:98.8, productremaining:6},
{id:13, number:13, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Straw Cape", productcoinname:"", productquality:63.5, productremaining:7},
{id:20, number:20, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Brick", productcoinname:"", productquality:92.7, productremaining:60},
{id:20, number:20, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:2, productname:"Troll Meat", productcoinname:"", productquality:130.5, productremaining:5},
{id:21, number:21, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Camomile", productcoinname:"", productquality:22.8, productremaining:1},
{id:21, number:21, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Exquisite Belt", productcoinname:"", productquality:45.1, productremaining:3},
{id:21, number:21, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Miner's Helm", productcoinname:"", productquality:104.5, productremaining:2},
{id:21, number:21, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Druid's Ring", productcoinname:"", productquality:29.8, productremaining:1},
{id:27, number:27, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:75, productname:"Bonesaw", productcoinname:"", productquality:222.0, productremaining:1},
{id:27, number:27, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Metal Saw", productcoinname:"", productquality:132.0, productremaining:1},
{id:28, number:28, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:60, productname:"Grand Brilliant Turquoise", productcoinname:"", productquality:11.0, productremaining:2},
{id:28, number:28, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:35, productname:"Bunny Slippers", productcoinname:"", productquality:107.3, productremaining:1},
{id:28, number:28, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Ball Clay", productcoinname:"", productquality:52.0, productremaining:6},
{id:29, number:29, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:120, productname:"Thane's Ring", productcoinname:"", productquality:188.5, productremaining:1},
{id:29, number:29, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Mammoth Tusk", productcoinname:"", productquality:304.0, productremaining:2},
{id:29, number:29, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:60, productname:"Thane's Ring", productcoinname:"", productquality:108.9, productremaining:1},
{id:30, number:30, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Battleaxe of the Twelfth Bay", productcoinname:"", productquality:194.1, productremaining:1},
{id:30, number:30, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:130, productname:"Metal Saw", productcoinname:"", productquality:239.2, productremaining:1},
{id:30, number:30, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:60, productname:"Metal Axe", productcoinname:"", productquality:227.8, productremaining:2},
{id:30, number:30, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Stone Axe", productcoinname:"", productquality:130.3, productremaining:1},
{id:30, number:30, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Cachalot Charm", productcoinname:"", productquality:149.4, productremaining:1},
{id:31, number:31, pricename:"Leather", pricecoinname:"", pricequality:0, pricenumber:1, productname:"6 coins of Silver", productcoinname:"Thaler", productquality:0, productremaining:7},
{id:31, number:31, pricename:"Silk Thread", pricecoinname:"", pricequality:0, pricenumber:1, productname:"8 coins of Silver", productcoinname:"Thaler", productquality:0, productremaining:5},
{id:31, number:31, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Stone Axe", productcoinname:"", productquality:284.8, productremaining:2},
{id:31, number:31, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:75, productname:"Pickaxe", productcoinname:"", productquality:205.9, productremaining:1},
{id:32, number:32, pricename:"Driftkelp", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Coin of Gold", productcoinname:"Crown", productquality:0, productremaining:10},
{id:32, number:32, pricename:"Raw Cachalot", pricecoinname:"", pricequality:0, pricenumber:1, productname:"2 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:6},
{id:32, number:32, pricename:"Golden Eagle Feather", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:3},
{id:32, number:32, pricename:"Rainbow Shell", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:3},
{id:32, number:32, pricename:"Camomile", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Coin of Gold", productcoinname:"Crown", productquality:0, productremaining:10},
{id:33, number:33, pricename:"Heartwood Leaves", pricecoinname:"", pricequality:0, pricenumber:1, productname:"4 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:10},
{id:33, number:33, pricename:"Heartwood Leaves", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:8},
{id:33, number:33, pricename:"Salt Crystals", pricecoinname:"", pricequality:0, pricenumber:1, productname:"10 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:5},
{id:33, number:33, pricename:"Salt Crystals", pricecoinname:"", pricequality:0, pricenumber:1, productname:"15 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:2},
{id:33, number:33, pricename:"Salt Crystals", pricecoinname:"", pricequality:0, pricenumber:1, productname:"20 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:3},
{id:34, number:34, pricename:"Peculiar Flotsam", pricecoinname:"", pricequality:0, pricenumber:1, productname:"4 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:10},
{id:34, number:34, pricename:"Peculiar Flotsam", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:3},
{id:34, number:34, pricename:"Edelweiß", pricecoinname:"", pricequality:0, pricenumber:1, productname:"8 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:5},
{id:34, number:34, pricename:"Glimmermoss", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:10},
{id:34, number:34, pricename:"Ant Soldiers", pricecoinname:"", pricequality:0, pricenumber:1, productname:"2 coins of Silver", productcoinname:"Thaler", productquality:0, productremaining:8},
{id:45, number:45, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Treeplanter's Pot", productcoinname:"", productquality:0, productremaining:4},
{id:45, number:45, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Notes of a Foul Symphony", productcoinname:"", productquality:1.0, productremaining:1},
{id:45, number:45, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Tiny Brilliant Turquoise", productcoinname:"", productquality:18.0, productremaining:9},
{id:46, number:46, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:180, productname:"Grand Brilliant Ruby", productcoinname:"", productquality:10.0, productremaining:1},
{id:46, number:46, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:120, productname:"Fair Brilliant Ruby", productcoinname:"", productquality:10.0, productremaining:1},
{id:46, number:46, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Fair Brilliant Diamond", productcoinname:"", productquality:17.0, productremaining:1},
{id:46, number:46, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:65, productname:"Large Brilliant Dust Jewel", productcoinname:"", productquality:0, productremaining:3},
{id:46, number:46, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Fair Brilliant Dust Jewel", productcoinname:"", productquality:0, productremaining:3},
{id:47, number:47, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Honey Wayband", productcoinname:"", productquality:59.5, productremaining:7},
{id:47, number:47, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Stitch Patch", productcoinname:"", productquality:86.2, productremaining:3},
{id:47, number:47, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Mud Ointment", productcoinname:"", productquality:60.1, productremaining:5},
{id:47, number:47, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Ant Paste", productcoinname:"", productquality:21.4, productremaining:5},
{id:47, number:47, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Kelp Cream", productcoinname:"", productquality:47.4, productremaining:5},
{id:48, number:48, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Yarrow", productcoinname:"", productquality:37.2, productremaining:6},
{id:48, number:48, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Rootfill", productcoinname:"", productquality:35.0, productremaining:2},
{id:48, number:48, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Gauze", productcoinname:"", productquality:43.7, productremaining:5},
{id:48, number:48, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Hartshorn Salve", productcoinname:"", productquality:57.7, productremaining:4},
{id:48, number:48, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Waybroad", productcoinname:"", productquality:15.6, productremaining:4},
{id:49, number:49, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Beaver Delights", productcoinname:"", productquality:19.0, productremaining:5},
{id:49, number:49, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Bucket", productcoinname:"", productquality:16.3, productremaining:1},
{id:49, number:49, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Ball Clay", productcoinname:"", productquality:59.4, productremaining:17},
{id:49, number:49, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:3, productname:"Bee Larvae", productcoinname:"", productquality:42.7, productremaining:29},
{id:49, number:49, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Ball Clay", productcoinname:"", productquality:59.4, productremaining:63},
{id:50, number:50, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:3, productname:"Scarab Talisman", productcoinname:"", productquality:86.4, productremaining:6},
{id:50, number:50, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Bat Guano", productcoinname:"", productquality:10.0, productremaining:1},
{id:50, number:50, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Notes of a Foul Symphony", productcoinname:"", productquality:10.0, productremaining:1},
{id:51, number:51, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Crying Yellow Onion", productcoinname:"", productquality:77.0, productremaining:1},
{id:51, number:51, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:5, productname:"Seer's Bowl", productcoinname:"", productquality:137.3, productremaining:5},
{id:51, number:51, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Black Ore", productcoinname:"", productquality:0, productremaining:27},
{id:52, number:52, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:28, productname:"Bronze Sword", productcoinname:"", productquality:178.9, productremaining:4},
{id:52, number:52, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:20, productname:"Bronze Sword", productcoinname:"", productquality:170.0, productremaining:1},
{id:52, number:52, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Metal Saw", productcoinname:"", productquality:177.5, productremaining:1},
{id:52, number:52, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Stone Axe", productcoinname:"", productquality:141.1, productremaining:2},
{id:54, number:54, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:9, productname:"0.04 kg of Opium", productcoinname:"", productquality:68.6, productremaining:18},
{id:54, number:54, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:8, productname:"0.04 kg of Opium", productcoinname:"", productquality:53.8, productremaining:12},
{id:54, number:54, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:7, productname:"Shears", productcoinname:"", productquality:115.5, productremaining:1},
{id:57, number:57, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:300, productname:"Pickaxe", productcoinname:"", productquality:258.6, productremaining:2},
{id:57, number:57, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Metal Saw", productcoinname:"", productquality:149.6, productremaining:3},
{id:57, number:57, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Metal Saw", productcoinname:"", productquality:180.6, productremaining:2},
{id:57, number:57, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Metal Saw", productcoinname:"", productquality:247.0, productremaining:2},
{id:57, number:57, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Shears", productcoinname:"", productquality:161.8, productremaining:2},
{id:58, number:58, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:300, productname:"Pickaxe", productcoinname:"", productquality:258.6, productremaining:2},
{id:58, number:58, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Metal Saw", productcoinname:"", productquality:149.6, productremaining:3},
{id:58, number:58, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Metal Saw", productcoinname:"", productquality:180.6, productremaining:2},
{id:58, number:58, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Metal Saw", productcoinname:"", productquality:247.0, productremaining:2},
{id:58, number:58, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Shears", productcoinname:"", productquality:161.8, productremaining:2},
{id:59, number:59, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Stone Axe", productcoinname:"", productquality:265.9, productremaining:2},
{id:59, number:59, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:280, productname:"Stone Axe", productcoinname:"", productquality:305.7, productremaining:1},
{id:59, number:59, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Metal Axe", productcoinname:"", productquality:160.2, productremaining:3},
{id:59, number:59, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Metal Axe", productcoinname:"", productquality:212.8, productremaining:2},
{id:59, number:59, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Metal Axe", productcoinname:"", productquality:246.5, productremaining:2},
{id:60, number:60, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Plate Greaves", productcoinname:"", productquality:127.0, productremaining:2},
{id:60, number:60, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:175, productname:"Bronze Plate", productcoinname:"", productquality:222.3, productremaining:2},
{id:60, number:60, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Bronze Helm", productcoinname:"", productquality:202.1, productremaining:2},
{id:61, number:61, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Hirdsman's Sword", productcoinname:"", productquality:180.6, productremaining:2},
{id:61, number:61, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:225, productname:"Plate Mail", productcoinname:"", productquality:171.0, productremaining:2},
{id:61, number:61, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:75, productname:"Plate Gauntlets", productcoinname:"", productquality:170.1, productremaining:2},
{id:61, number:61, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:75, productname:"Plate Boots", productcoinname:"", productquality:169.9, productremaining:2},
{id:61, number:61, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Plate Greaves", productcoinname:"", productquality:176.0, productremaining:2},
{id:62, number:62, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:20, productname:"Boar Spear", productcoinname:"", productquality:139.0, productremaining:3},
{id:62, number:62, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Boar Spear", productcoinname:"", productquality:173.8, productremaining:2},
{id:62, number:62, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Bronze Sword", productcoinname:"", productquality:270.8, productremaining:2},
{id:62, number:62, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Bronze Sword", productcoinname:"", productquality:164.6, productremaining:4},
{id:62, number:62, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Boar Spear", productcoinname:"", productquality:216.9, productremaining:1},
{id:63, number:63, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Frying Pan", productcoinname:"", productquality:164.2, productremaining:3},
{id:63, number:63, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Frying Pan", productcoinname:"", productquality:248.6, productremaining:2},
{id:63, number:63, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Frying Pan", productcoinname:"", productquality:305.6, productremaining:2},
{id:63, number:63, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:350, productname:"Gridiron", productcoinname:"", productquality:283.0, productremaining:1},
{id:63, number:63, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Gridiron", productcoinname:"", productquality:215.5, productremaining:1},
{id:67, number:67, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:300, productname:"Stone Axe", productcoinname:"", productquality:305.1, productremaining:7},
{id:67, number:67, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:250, productname:"Stone Axe", productcoinname:"", productquality:292.8, productremaining:1},
{id:67, number:67, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Stone Axe", productcoinname:"", productquality:285.8, productremaining:1},
{id:67, number:67, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Stone Axe", productcoinname:"", productquality:279.8, productremaining:1},
{id:67, number:67, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Stone Axe", productcoinname:"", productquality:220.5, productremaining:2},
{id:68, number:68, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:300, productname:"Bonesaw", productcoinname:"", productquality:240.0, productremaining:1},
{id:68, number:68, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Bonesaw", productcoinname:"", productquality:210.1, productremaining:1},
{id:68, number:68, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Bonesaw", productcoinname:"", productquality:201.6, productremaining:1},
{id:69, number:69, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Woodsman's Axe", productcoinname:"", productquality:172.8, productremaining:12},
{id:69, number:69, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Metal Axe", productcoinname:"", productquality:176.4, productremaining:6},
{id:69, number:69, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Metal Shovel", productcoinname:"", productquality:175.1, productremaining:6},
{id:69, number:69, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Scythe", productcoinname:"", productquality:171.3, productremaining:1},
{id:69, number:69, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Metal Saw", productcoinname:"", productquality:181.3, productremaining:2},
{id:70, number:70, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Pickaxe", productcoinname:"", productquality:179.7, productremaining:2},
{id:70, number:70, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Pickaxe", productcoinname:"", productquality:157.9, productremaining:12},
{id:70, number:70, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Smithy's Hammer", productcoinname:"", productquality:107.0, productremaining:1},
{id:71, number:71, pricename:"Bone Material", pricecoinname:"", pricequality:0, pricenumber:1, productname:"2 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:32},
{id:71, number:71, pricename:"Bone Material", pricecoinname:"", pricequality:0, pricenumber:1, productname:"3 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:32},
{id:71, number:71, pricename:"Bone Material", pricecoinname:"", pricequality:0, pricenumber:1, productname:"4 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:25},
{id:71, number:71, pricename:"Fouls of the Deep", pricecoinname:"", pricequality:0, pricenumber:1, productname:"20 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:1},
{id:71, number:71, pricename:"Bat Guano", pricecoinname:"", pricequality:0, pricenumber:1, productname:"40 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:5},
{id:72, number:72, pricename:"Fine Clay", pricecoinname:"", pricequality:0, pricenumber:1, productname:"2 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:9},
{id:72, number:72, pricename:"Fine Clay", pricecoinname:"", pricequality:0, pricenumber:1, productname:"5 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:12},
{id:72, number:72, pricename:"Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"20 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:6},
{id:72, number:72, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"90 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:7},
{id:73, number:73, pricename:"Bar of Gold", pricecoinname:"", pricequality:0, pricenumber:1, productname:"90 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:7},
{id:73, number:73, pricename:"Gold Pebbles", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Coin of Gold", productcoinname:"Crown", productquality:0, productremaining:6},
{id:73, number:73, pricename:"Bar of Silver", pricecoinname:"", pricequality:0, pricenumber:1, productname:"90 coins of Silver", productcoinname:"Thaler", productquality:0, productremaining:19},
{id:73, number:73, pricename:"Silver Nugget", pricecoinname:"", pricequality:0, pricenumber:1, productname:"9 coins of Silver", productcoinname:"Thaler", productquality:0, productremaining:10},
{id:75, number:75, pricename:"Meat", pricecoinname:"", pricequality:0, pricenumber:0, productname:"Coin of Gold", productcoinname:"Crown", productquality:0, productremaining:50},
{id:77, number:77, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:50, productname:"Hunter's Bow", productcoinname:"", productquality:103.1, productremaining:1},
{id:77, number:77, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Morels", productcoinname:"", productquality:22.8, productremaining:1},
{id:77, number:77, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Cave Lantern", productcoinname:"", productquality:26.4, productremaining:5},
{id:79, number:79, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Bear Coat", productcoinname:"", productquality:122.0, productremaining:1},
{id:79, number:79, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:15, productname:"Metal Saucière", productcoinname:"", productquality:161.3, productremaining:2},
{id:80, number:80, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:15, productname:"Bronze Sword", productcoinname:"", productquality:142.6, productremaining:1},
{id:80, number:80, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Frying Pan", productcoinname:"", productquality:169.5, productremaining:2},
{id:80, number:80, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Cast Iron Trivet", productcoinname:"", productquality:161.8, productremaining:2},
{id:82, number:82, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:2, productname:"Large Rough Sapphire", productcoinname:"", productquality:25.0, productremaining:2},
{id:82, number:82, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Bar of Cast Iron", productcoinname:"", productquality:55.7, productremaining:10},
{id:82, number:82, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Fairy Mushroom", productcoinname:"", productquality:44.0, productremaining:3},
{id:82, number:82, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:2, productname:"Cave Lantern", productcoinname:"", productquality:10.0, productremaining:2},
{id:104, number:104, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Pumpkin Pie", productcoinname:"", productquality:103.6, productremaining:44},
{id:104, number:104, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Delicious Deer Dog", productcoinname:"", productquality:104.0, productremaining:46},
{id:104, number:104, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Blueberry Pie", productcoinname:"", productquality:93.7, productremaining:3},
{id:104, number:104, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:3, productname:"Butter-steamed Cavebulb", productcoinname:"", productquality:103.3, productremaining:32},
{id:105, number:105, pricename:"Bar of Steel", pricecoinname:"", pricequality:0, pricenumber:1, productname:"8 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:16},
{id:105, number:105, pricename:"Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"25 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:4},
{id:105, number:105, pricename:"Heartwood Leaves", pricecoinname:"", pricequality:0, pricenumber:1, productname:"4 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:2},
{id:106, number:106, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Hunter's Bow", productcoinname:"", productquality:200.6, productremaining:3},
{id:106, number:106, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Bear Coat", productcoinname:"", productquality:120.7, productremaining:1},
{id:106, number:106, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Moose Hide Jacket", productcoinname:"", productquality:105.0, productremaining:1},
{id:109, number:109, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Large Brilliant Amethyst", productcoinname:"", productquality:23.0, productremaining:2},
{id:109, number:109, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:75, productname:"Grand Brilliant Amethyst", productcoinname:"", productquality:20.0, productremaining:1},
{id:110, number:110, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Fair Brilliant Opal", productcoinname:"", productquality:28.0, productremaining:3},
{id:110, number:110, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Large Brilliant Topaz", productcoinname:"", productquality:15.0, productremaining:2},
{id:110, number:110, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Large Brilliant Emerald", productcoinname:"", productquality:10.0, productremaining:3},
{id:110, number:110, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Grand Brilliant Topaz", productcoinname:"", productquality:10.0, productremaining:4},
{id:110, number:110, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Large Brilliant Opal", productcoinname:"", productquality:10.0, productremaining:2},
{id:114, number:114, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Sketchbook, 1 page", productcoinname:"", productquality:0, productremaining:5},
{id:115, number:115, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Golden Cat", productcoinname:"", productquality:153.4, productremaining:5},
{id:116, number:116, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"0.09 kg of Opium", productcoinname:"", productquality:113.1, productremaining:1},
{id:116, number:116, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Ant Farm", productcoinname:"", productquality:30.8, productremaining:5},
{id:120, number:120, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Silk Thread", productcoinname:"", productquality:125.1, productremaining:11},
{id:120, number:120, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Silk Cloth", productcoinname:"", productquality:134.0, productremaining:3},
{id:120, number:120, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:120, productname:"Merchant's Robe", productcoinname:"", productquality:197.3, productremaining:1},
{id:120, number:120, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Mother of Pearl", productcoinname:"", productquality:74.0, productremaining:1},
{id:141, number:141, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:60, productname:"Metal Axe", productcoinname:"", productquality:231.3, productremaining:1},
{id:141, number:141, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Metal Saw", productcoinname:"", productquality:246.6, productremaining:1},
{id:141, number:141, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Monocle", productcoinname:"", productquality:205.2, productremaining:4},
{id:141, number:141, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:50, productname:"Clothier's Thimble", productcoinname:"", productquality:202.9, productremaining:2},
{id:142, number:142, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Stone Axe", productcoinname:"", productquality:253.3, productremaining:3},
{id:142, number:142, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Stone Axe", productcoinname:"", productquality:295.5, productremaining:1},
{id:142, number:142, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:120, productname:"Metal Saw", productcoinname:"", productquality:238.1, productremaining:1},
{id:143, number:143, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Pickaxe", productcoinname:"", productquality:206.2, productremaining:1},
{id:143, number:143, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Pickaxe", productcoinname:"", productquality:235.1, productremaining:2},
{id:143, number:143, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Treeplanter's Pot", productcoinname:"", productquality:0, productremaining:4},
{id:143, number:143, pricename:"River Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"25 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:4},
{id:143, number:143, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:180, productname:"Stone Axe", productcoinname:"", productquality:316.6, productremaining:1},
{id:144, number:144, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Occult Ring", productcoinname:"", productquality:208.4, productremaining:2},
{id:144, number:144, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"100 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:1},
{id:144, number:144, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:2, productname:"Troll Belt", productcoinname:"", productquality:134.3, productremaining:1},
{id:144, number:144, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Thane's Ring", productcoinname:"", productquality:208.8, productremaining:2},
{id:144, number:144, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Merchant's Ring", productcoinname:"", productquality:209.2, productremaining:3},
{id:145, number:145, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:15, productname:"Suckling's Maw", productcoinname:"", productquality:11.1, productremaining:14},
{id:145, number:145, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Suckling's Maw", productcoinname:"", productquality:5.4, productremaining:16},
{id:145, number:145, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:30, productname:"Suckling's Maw", productcoinname:"", productquality:15.4, productremaining:21},
{id:146, number:146, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Zope", productcoinname:"", productquality:16.3, productremaining:17},
{id:146, number:146, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Cavelacanth", productcoinname:"", productquality:18.8, productremaining:8},
{id:146, number:146, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Cave Sculpin", productcoinname:"", productquality:9.2, productremaining:1},
{id:146, number:146, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Tench", productcoinname:"", productquality:18.0, productremaining:7},
{id:146, number:146, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:2, productname:"Dried Filet of Pale Ghostfish", productcoinname:"", productquality:20.0, productremaining:32},
{id:149, number:149, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Chives", productcoinname:"", productquality:57.0, productremaining:5},
{id:149, number:149, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Dill", productcoinname:"", productquality:67.0, productremaining:5},
{id:149, number:149, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Kvann", productcoinname:"", productquality:55.0, productremaining:5},
{id:149, number:149, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Sage", productcoinname:"", productquality:65.0, productremaining:5},
{id:150, number:150, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Bucket", productcoinname:"", productquality:10.2, productremaining:1},
{id:151, number:151, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Boar Spear", productcoinname:"", productquality:138.3, productremaining:1},
{id:151, number:151, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Boreworm Mask", productcoinname:"", productquality:145.5, productremaining:1},
{id:151, number:151, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Spectacles", productcoinname:"", productquality:108.9, productremaining:1},
{id:152, number:152, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Blueberry Pie", productcoinname:"", productquality:76.5, productremaining:63},
{id:152, number:152, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Delicious Deer Dog", productcoinname:"", productquality:76.9, productremaining:14},
{id:152, number:152, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Cow Chorizo", productcoinname:"", productquality:54.1, productremaining:16},
{id:169, number:169, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Beast Ring", productcoinname:"", productquality:68.3, productremaining:1},
{id:169, number:169, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Golden Eagle Meat", productcoinname:"", productquality:50.0, productremaining:4},
{id:169, number:169, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:6, productname:"Ruby Dragonfly", productcoinname:"", productquality:20.0, productremaining:1},
{id:170, number:170, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:5, productname:"Raw Beaver", productcoinname:"", productquality:72.0, productremaining:9},
{id:170, number:170, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Beaver Teeth", productcoinname:"", productquality:69.0, productremaining:1},
{id:170, number:170, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Golden Eagle Feather", productcoinname:"", productquality:50.0, productremaining:2},
{id:170, number:170, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Scratch-Marked Bark", productcoinname:"", productquality:10.0, productremaining:2},
{id:170, number:170, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Lucky Rabbit's Foot", productcoinname:"", productquality:10.0, productremaining:2},
{id:171, number:171, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Withercorn", productcoinname:"", productquality:10.0, productremaining:2},
{id:171, number:171, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Beaver Tail", productcoinname:"", productquality:36.0, productremaining:2},
{id:171, number:171, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Mother of Pearl", productcoinname:"", productquality:75.0, productremaining:1},
{id:171, number:171, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Golden Eagle Talon", productcoinname:"", productquality:50.0, productremaining:1},
{id:175, number:175, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Fairy Mushroom", productcoinname:"", productquality:20.0, productremaining:23},
{id:175, number:175, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:7, productname:"Box of Matches", productcoinname:"", productquality:20.4, productremaining:7},
{id:175, number:175, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Crying Yellow Onion", productcoinname:"", productquality:44.0, productremaining:2},
{id:175, number:175, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Peppercorn", productcoinname:"", productquality:40.0, productremaining:15},
{id:176, number:176, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Stalagoomba", productcoinname:"", productquality:10.0, productremaining:1},
{id:186, number:186, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Board of King's Oak", productcoinname:"", productquality:150.4, productremaining:4},
{id:186, number:186, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84.0, productremaining:8},
{id:186, number:186, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Board of King's Oak", productcoinname:"", productquality:150.4, productremaining:7},
{id:186, number:186, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84.0, productremaining:7},
{id:186, number:186, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84.0, productremaining:8},
{id:187, number:187, pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Ball Clay", productcoinname:"", productquality:53.0, productremaining:53},
{id:187, number:187, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Feldspar", productcoinname:"", productquality:340.8, productremaining:52},
{id:187, number:187, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Feldspar", productcoinname:"", productquality:312.3, productremaining:49},
{id:188, number:188, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Forge Ring", productcoinname:"", productquality:162.2, productremaining:2},
{id:188, number:188, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Merchant's Ring", productcoinname:"", productquality:166.5, productremaining:2},
{id:188, number:188, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:65, productname:"Clothier's Thimble", productcoinname:"", productquality:166.5, productremaining:2},
{id:188, number:188, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:130, productname:"Thane's Ring", productcoinname:"", productquality:237.7, productremaining:1},
{id:188, number:188, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:145, productname:"Occult Ring", productcoinname:"", productquality:296.1, productremaining:2},
{id:189, number:189, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:180, productname:"Stone Axe", productcoinname:"", productquality:312.5, productremaining:3},
{id:189, number:189, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Pickaxe", productcoinname:"", productquality:244.5, productremaining:1},
{id:189, number:189, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:400, productname:"Metal Saw", productcoinname:"", productquality:285.5, productremaining:1},
{id:189, number:189, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:170, productname:"Metal Axe", productcoinname:"", productquality:288.4, productremaining:2},
{id:189, number:189, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:400, productname:"Pickaxe", productcoinname:"", productquality:273.2, productremaining:1},
{id:190, number:190, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Pickaxe", productcoinname:"", productquality:190.2, productremaining:2},
{id:190, number:190, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Boar Spear", productcoinname:"", productquality:276.4, productremaining:1},
{id:190, number:190, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Metal Saw", productcoinname:"", productquality:189.2, productremaining:2},
{id:190, number:190, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Bonesaw", productcoinname:"", productquality:196.6, productremaining:2},
{id:190, number:190, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Stone Axe", productcoinname:"", productquality:219.9, productremaining:1},
{id:191, number:191, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Monocle", productcoinname:"", productquality:262.3, productremaining:1},
{id:191, number:191, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Bronze Sword", productcoinname:"", productquality:164.2, productremaining:1},
{id:191, number:191, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Bronze Sword", productcoinname:"", productquality:147.8, productremaining:1},
{id:191, number:191, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Bronze Sword", productcoinname:"", productquality:107.0, productremaining:1},
{id:195, number:195, pricename:"Heartwood Leaves", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Coin of Gold", productcoinname:"Crown", productquality:0, productremaining:31},
{id:195, number:195, pricename:"Salt Crystals", pricecoinname:"", pricequality:0, pricenumber:1, productname:"10 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:24},
{id:195, number:195, pricename:"Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"30 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:9},
{id:199, number:199, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Forge Ring", productcoinname:"", productquality:254.9, productremaining:3},
{id:199, number:199, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"50 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:7},
{id:199, number:199, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Ring of Brodgar", productcoinname:"", productquality:233.9, productremaining:7},
{id:199, number:199, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Clothier's Thimble", productcoinname:"", productquality:255.4, productremaining:2},
{id:200, number:200, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Cachalot Charm", productcoinname:"", productquality:177.3, productremaining:7},
{id:200, number:200, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"15 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:23},
{id:200, number:200, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:6, productname:"6 coins of Gold", productcoinname:"Crown", productquality:0, productremaining:5},
{id:202, number:202, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Stone Axe", productcoinname:"", productquality:200.9, productremaining:2},
{id:202, number:202, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Stone Axe", productcoinname:"", productquality:252.4, productremaining:1},
{id:202, number:202, pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:450, productname:"Stone Axe", productcoinname:"", productquality:279.4, productremaining:5},
{id:202, number:202, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:9, productname:"Stone Axe", productcoinname:"", productquality:338.6, productremaining:3},
{id:202, number:202, pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:4, productname:"Stone Axe", productcoinname:"", productquality:279.4, productremaining:5},
]