var tableData = [
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Heartwood Leaves", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Coin of Gold", productcoinname:"Crown", productquality:undefined, productremaining:31},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Salt Crystals", pricecoinname:"", pricequality:0, pricenumber:1, productname:"10 coins of Gold", productcoinname:"Crown", productquality:undefined, productremaining:24},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"30 coins of Gold", productcoinname:"Crown", productquality:undefined, productremaining:10},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Monocle", productcoinname:"", productquality:262.28955078125, productremaining:1},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Bronze Sword", productcoinname:"", productquality:164.17959594726562, productremaining:1},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Bronze Sword", productcoinname:"", productquality:147.8270263671875, productremaining:1},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Bronze Sword", productcoinname:"", productquality:107.0254898071289, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Pickaxe", productcoinname:"", productquality:190.1641387939453, productremaining:2},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Boar Spear", productcoinname:"", productquality:276.42633056640625, productremaining:1},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Metal Saw", productcoinname:"", productquality:189.20098876953125, productremaining:2},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Bonesaw", productcoinname:"", productquality:196.61000061035156, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Stone Axe", productcoinname:"", productquality:219.86529541015625, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:180, productname:"Stone Axe", productcoinname:"", productquality:312.52191162109375, productremaining:3},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:200, productname:"Pickaxe", productcoinname:"", productquality:244.5069122314453, productremaining:1},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:450, productname:"Metal Saw", productcoinname:"", productquality:285.5372619628906, productremaining:1},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:170, productname:"Metal Axe", productcoinname:"", productquality:288.4122619628906, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:500, productname:"Pickaxe", productcoinname:"", productquality:273.2481994628906, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Forge Ring", productcoinname:"", productquality:162.2207794189453, productremaining:2},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:80, productname:"Merchant's Ring", productcoinname:"", productquality:166.47433471679688, productremaining:2},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:65, productname:"Clothier's Thimble", productcoinname:"", productquality:166.51705932617188, productremaining:2},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:130, productname:"Thane's Ring", productcoinname:"", productquality:237.699951171875, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:145, productname:"Occult Ring", productcoinname:"", productquality:296.1067199707031, productremaining:2},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Ball Clay", productcoinname:"", productquality:53, productremaining:53},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Feldspar", productcoinname:"", productquality:340.7951965332031, productremaining:52},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Feldspar", productcoinname:"", productquality:316.2951965332031, productremaining:56},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Board of King's Oak", productcoinname:"", productquality:150.43270874023438, productremaining:4},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84, productremaining:11},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Board of King's Oak", productcoinname:"", productquality:150.43270874023438, productremaining:7},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84, productremaining:8},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Block of Spruce", productcoinname:"", productquality:84, productremaining:8},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:3, productname:"Fairy Mushroom", productcoinname:"", productquality:20, productremaining:23},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:7, productname:"Box of Matches", productcoinname:"", productquality:20.27090835571289, productremaining:3},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:30, productname:"Crying Yellow Onion", productcoinname:"", productquality:44, productremaining:2},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Heartwood Leaves", productcoinname:"", productquality:10, productremaining:9},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Peppercorn", productcoinname:"", productquality:40, productremaining:15},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Withercorn", productcoinname:"", productquality:10, productremaining:2},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Beaver Tail", productcoinname:"", productquality:36, productremaining:2},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Mother of Pearl", productcoinname:"", productquality:75, productremaining:1},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:2, productname:"Bucket", productcoinname:"", productquality:11.775439262390137, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Golden Eagle Talon", productcoinname:"", productquality:50, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:5, productname:"Raw Beaver", productcoinname:"", productquality:72, productremaining:9},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Beaver Teeth", productcoinname:"", productquality:69, productremaining:1},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:4, productname:"Golden Eagle Feather", productcoinname:"", productquality:50, productremaining:2},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Scratch-Marked Bark", productcoinname:"", productquality:10, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Lucky Rabbit's Foot", productcoinname:"", productquality:10, productremaining:2},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Beast Ring", productcoinname:"", productquality:68.26375579833984, productremaining:1},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:1, productname:"Golden Eagle Meat", productcoinname:"", productquality:50, productremaining:4},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Blueberry Pie", productcoinname:"", productquality:76.46329498291016, productremaining:63},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Delicious Deer Dog", productcoinname:"", productquality:76.9124984741211, productremaining:14},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:1, productname:"Cow Chorizo", productcoinname:"", productquality:54.125, productremaining:16},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Boar Spear", productcoinname:"", productquality:138.2828369140625, productremaining:1},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:40, productname:"Boreworm Mask", productcoinname:"", productquality:145.5, productremaining:1},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Spectacles", productcoinname:"", productquality:108.86480712890625, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Box of Matches", productcoinname:"", productquality:40.24791717529297, productremaining:1},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:10, productname:"Bucket", productcoinname:"", productquality:10.156197547912598, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Chives", productcoinname:"", productquality:57, productremaining:5},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Dill", productcoinname:"", productquality:67, productremaining:5},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Kvann", productcoinname:"", productquality:55, productremaining:5},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:5, productname:"Sage", productcoinname:"", productquality:65, productremaining:5},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Zope", productcoinname:"", productquality:16.25, productremaining:17},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Cavelacanth", productcoinname:"", productquality:18.75, productremaining:8},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:2, productname:"Cave Sculpin", productcoinname:"", productquality:9.237841606140137, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:15, productname:"Suckling's Maw", productcoinname:"", productquality:11.399999618530273, productremaining:14},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:10, productname:"Suckling's Maw", productcoinname:"", productquality:1.940000057220459, productremaining:10},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:90, productname:"Occult Ring", productcoinname:"", productquality:208.37841796875, productremaining:2},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"100 coins of Gold", productcoinname:"Crown", productquality:undefined, productremaining:4},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:2, productname:"Troll Belt", productcoinname:"", productquality:134.3276824951172, productremaining:1},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Thane's Ring", productcoinname:"", productquality:208.8185577392578, productremaining:2},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:70, productname:"Merchant's Ring", productcoinname:"", productquality:209.24610900878906, productremaining:3},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Pickaxe", productcoinname:"", productquality:206.2378387451172, productremaining:1},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:150, productname:"Pickaxe", productcoinname:"", productquality:235.08460998535156, productremaining:2},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:100, productname:"Treeplanter's Pot", productcoinname:"", productquality:undefined, productremaining:4},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"River Pearl", pricecoinname:"", pricequality:0, pricenumber:1, productname:"25 coins of Gold", productcoinname:"Crown", productquality:undefined, productremaining:6},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:180, productname:"Stone Axe", productcoinname:"", productquality:316.5965576171875, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:15, productname:"Stone Axe", productcoinname:"", productquality:253.25210571289062, productremaining:3},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:50, productname:"Stone Axe", productcoinname:"", productquality:294.9619445800781, productremaining:2},
{id:4, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:120, productname:"Metal Saw", productcoinname:"", productquality:238.10232543945312, productremaining:1},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:20, productname:"Bonesaw", productcoinname:"", productquality:209.25, productremaining:1},
{id:1, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:60, productname:"Metal Axe", productcoinname:"", productquality:231.28201293945312, productremaining:1},
{id:2, marketgroup:"Test", stallnumber:"1", pricename:"Game Time Token", pricecoinname:"", pricequality:0, pricenumber:1, productname:"Metal Saw", productcoinname:"", productquality:246.61134338378906, productremaining:1},
{id:3, marketgroup:"Test", stallnumber:"1", pricename:"Gold Coins", pricecoinname:"Crown", pricequality:0, pricenumber:25, productname:"Monocle", productcoinname:"", productquality:205.155029296875, productremaining:5},
{id:5, marketgroup:"Test", stallnumber:"1", pricename:"Silver Coins", pricecoinname:"Thaler", pricequality:0, pricenumber:50, productname:"Clothier's Thimble", productcoinname:"", productquality:202.88534545898438, productremaining:2},
]

var table = new Tabulator("#markettable", {
    data:tableData, //set initial table data
    columns:[
        {title:"Market Group", field:"marketgroup"},
        {title:"Stall Number", field:"stallnumber"},
        {title:"Price Name", field:"pricename"},
        {title:"Price Coin Name", field:"pricecoinname"},
		{title:"Price Quality", field:"pricequality"},
        {title:"Price Number", field:"pricenumber"},
        {title:"Product Name", field:"productname"},
        {title:"Product Coin Name", field:"productcoinname"},
        {title:"Product Quality", field:"productquality"},
        {title:"Product Remaining", field:"productremaining"},
    ],
});
